### ISSUE TITLE
14-bit MIDI support

### ISSUE THREAD

**Issue by robinparmar** [martinpavlas/electra.one#14]
Support for 14-bit MIDI would distinguish the Electra One from most other controllers. The ability to send 16384 values of a parameter instead of only 128 has audible benefits when controlling pitch, filter cut-off frequency, amplitude, etc. Many software environments (NI Reaktor, Max) are ready to receive such hi-resolution data.

There are several considerations.

**Method**: The optimal implementation for encoding high resolution MIDI uses NRPN as documented by [Phil Rees](http://www.philrees.co.uk/nrpnq.htm).

**Editor Interface**: Fader items would need a toggle for the user to select "normal" (7 bit) or "high" (14 bit) resolution. This would change the Max value limit from 127 to 16383. No further change is needed.

**Hardware interface**: The Electra would need to smooth high resolution values for showing the fader graphics, and allow numbers higher than 127 to be displayed.

**Controllers**: The physical encoders might perhaps only be read at 10 bits, which would need to be extrapolated and smoothed to 14 bits. However, even this has real value over a mere 7 bits. Entering values might need to be handled differently if the control is in high resolution mode, since it should be possible to increment through individual numbers while also rapidly changing values. This is a matter of changing the acceleration curve.

Note: Existing high resolution controllers include the Behringer BCR-2000 and FaderFox line. DJ controllers such as the Vestax VCI-300 and Numark NS7 use it for pitch change. Synths like the Moog Phatty, Model 15, Alesis Andromeda, etc. have some implementation.

**Comment by martinpavlas** [comment]
Resolved in firmware 0.9.2 and the editor app.

14-bit CC, NRPN, RPN, and custom SysEx messages can be now assigned to the controls.

**Comment by robinparmar** [comment]
Wow!

It will take me two weeks to get back to this, but then hope to be more
active again.

---
Robin Parmar

w: robinparmar.com | <http://robinparmar.com> stolenmirror.com | 7prs.org |
<http://7prs.org>dmarc.ie <http://7prs.org>
e: robin@robinparmar.com
p: +353 (0) 87 286 2678
