### ISSUE TITLE
Electra one power problen after freezing 

### ISSUE THREAD

**Issue by simonhorn74** [martinpavlas/electra.one#15]
Hi,
Just powered up my Electra One and within 30 mins it froze so I unplugged it to reset. Now it won't power up at all. Any ideas? 
Simon

**Comment by martinpavlas** [comment]
please refer to [Hard reset of Electra](https://github.com/martinpavlas/electra.one/wiki/Hard-reset-when-Electra-is-not-starting-up). It should recover your Electra. As part of the procedure update to 0.9.8.1 it has the issue with freezing resolved.
