### ISSUE TITLE
On list items with overlay (with lots of sub items), if you rotate the knob counter clockwise too fast, it sends the last value instead of the first value.

### ISSUE THREAD

**Issue by pmgdias** [martinpavlas/electra.one#18]
If you have 30 overlay items (with values from 0 to 30) within a list item., if you rotate the corresponding knob too fast counter clockwise then it sends 30 instead of 0.

Its reproducible with the attached preset on most of the list items and by checking the Electra One Console application.

[MicroMonsta (14).zip](https://github.com/martinpavlas/electra.one/files/4011402/MicroMonsta.14.zip)

**Comment by martinpavlas** [comment]
I hope this one has been resolved. I cannot reproduce it with current line of firmware.
