### ISSUE TITLE
Bidirectional communication with VST plug-ins 

### ISSUE THREAD

**Issue by markusschloesser** [martinpavlas/electra.one#21]
Bidirectional communication for VST plug-ins, so that parameter changes done by mouse, automation or another controller are reflected on the Elektra One. Admittedly I don't know if VSTs send CC or NRPN when changing parameters or presets (probably not for the latter)

**Comment by martinpavlas** [comment]
Supported by DAWs. see https://docs.electra.one/tutorials/abletonvst.html
