### ISSUE TITLE
There seems to be a limit on how many list / overlay items you can have per preset

### ISSUE THREAD

**Issue by pmgdias** [martinpavlas/electra.one#23]
Last three parameters on page three seem to have corrupted overlay items. 

Maybe due to some limit on overlay memory per preset ?

Example attached.

[MicroMonsta (23).zip](https://github.com/martinpavlas/electra.one/files/4014503/MicroMonsta.23.zip)

**Comment by martinpavlas** [comment]
The limit is now 256 items per list
