### ISSUE TITLE
NRPN Values with separate MSB and LSB values

### ISSUE THREAD

**Issue by jonpauldavies** [martinpavlas/electra.one#29]
Synths like the Elektron Analog Four Mk2 specify NRPN as 2 separate MSB and LSB values.

**For example:**

Parameter |  NRPN MSB | NRPN LSB 
---------- | ----------- | --------
OSC1 AM | 1 | 30

How can we specify these in controls?

**Comment by martinpavlas** [comment]
the formula is: 

`parameter = MSB * 127 + LSB`

it means in your example it is:

`157 = 1 * 127 + 30`

you can specify the parameter numbers using this formula. Can you test it?

I will schedule an adjustment of the editor so that it will be possible to enter NRPN parameter as MSB and LSB.

**Comment by markusschloesser** [comment]
i will need this as well for the FS1R.
Additionally: can I already enter values in hex? If not, I'll open another issue

**Comment by martinpavlas** [comment]
I will add hex / dec switch to this. No need to open a separate issue.

**Comment by martinpavlas** [comment]
Resolved. NRPN and CC14 message type can be specified now in MSB/LSB format. Optional swicthed between Hex and Dec representation.
