### ISSUE TITLE
Operational issue

### ISSUE THREAD

**Issue by syncloop** [martinpavlas/electra.one#30]
Electra One freezes with the following operations.
(Firmware 0.9.8.1)

1. Push [MENU] button
2. Push [PRESETS] button
3. Select empty preset
4. Push [PATCH REQUEST] button

**Comment by martinpavlas** [comment]
Hi there,

I was not able to replicate this issue. Would you, please, try to update firmware to 0.9.10 and test it again? [0.9.10](https://github.com/martinpavlas/electra.one/releases/tag/0.9.10) was released today.

Thank you!

**Comment by syncloop** [comment]
I updated firmware to 0.9.10 and it worked fine.

Thanks for your work !

**Comment by martinpavlas** [comment]
very happy to hear. I will close the issue then. Thanks for the feedback.
