### ISSUE TITLE
after update to 0.9.10 wrong values shown

### ISSUE THREAD

**Issue by markusschloesser** [martinpavlas/electra.one#32]
I updated to 0.9.10 and now the top left controller shows values from another controller on the device itself even though when doing "load from electra" the web ui shows correct values.
In this case Elektra shows on "cutoff" the values from "filter type"
![elektra cutoff Annotation 2020-01-07 122621](https://user-images.githubusercontent.com/59286549/71892393-1309bb80-3149-11ea-93a5-1b01d85205a0.jpg)
![elektra filter types Annotation 2020-01-07 122604](https://user-images.githubusercontent.com/59286549/71892394-1309bb80-3149-11ea-9b48-ba2864e7556b.jpg)

**Comment by martinpavlas** [comment]
Hi Markus, I am in the middle of "release". Would you try to do the same in https://dev.electra.one/ editor? ie. Load the preset from Electra to the editor and then send it back to Electra? please let me know if the issue persists.

**Comment by markusschloesser** [comment]
that fixed it, thanks!
FYI
1. I needed to reboot Elektra to work with the dev.
2. Also I needed to flash the firmware twice. After flashing only once touch screen support wasn't working

**Comment by martinpavlas** [comment]
thanks. production editor will be updated later today, till it is announced, please stay on dev. I will let you know when you you can switch back to editor.

I will take a look at the two points you just sent.

**Comment by markusschloesser** [comment]
One additional bug: the new big overlay feature (great Btw!) doesn't show text "values" only numbers. So even if for example I have "filter type" set to values 12db 24db and svf, the big slider only shows 1,2,3

**Comment by martinpavlas** [comment]
This is the first kickoff of the on-screen control. We will keep improving that. Regarding this, I would suggest to switch the control from fader to list. You will get only a selection of discrete list items.
