### ISSUE TITLE
preset management in Editor

### ISSUE THREAD

**Issue by markusschloesser** [martinpavlas/electra.one#34]
Am I correct to assume, that in order to start a new preset, I have to load an empty preset on the HW and then request it in the editor? Because that doesn't work right now (0.9.11, loading existing ones works). 
Or is there any other way? I didn't find anything in the manual about it. 
How about a "New preset" button in the editor?

**Comment by martinpavlas** [comment]
Hi Markus, my workflow is:

1. hit "clear all", it creates an empty preset in the Editor
2. start working on the new preset
3. send it to Electra at any moment I want to see/use it on the HW

In upcoming release there will be first more permanent storage of presets on the Editor side, along with that or shortly after that we will introduce more "actions" on the editor side that will directly interact with Electra. "New preset" will be one of them.

**Comment by martinpavlas** [comment]
I believe this has been addressed in the new https://app.electra.one/ website
