### ISSUE TITLE
Can I make a button for "program change"?

### ISSUE THREAD

**Issue by christofmuc** [martinpavlas/electra.one#44]
Hi! I am using the online editor, and I can make a slider to select the bank, because that is CC 0, but how would I make a slider to select the program? This is a simple MIDI command, and not a CC, NRPN, or RPN AFAIK. Thanks for the help!

**Comment by markusschloesser** [comment]
Hey hey 😊😊 welcome! 
1. You can't currently, to be implemented in next firmware (currently in beta). (there is a workaround by directly editing the json) 
2. https://forum.electra.one/ is the place to discuss. Martin decided at one point that not everyone is comfortable with github.

**Comment by christofmuc** [comment]
@markusschloesser Thank you! Yes, enjoying to make my first experiments with the Electra One. Already fixed a couple of bugs in the KnobKraft adaptation for it, but still having some troubles with long sysex messages. I will go through the forums first, to try to catch up, thanks for pointing it out to me - I had completely missed how active they are now.

**Comment by markusschloesser** [comment]
Oh cool 😎 looking forward to it!
I'm currently busy with an ableton live remote script for the Mackie C4, that's why I haven't been bothering you 😉😂
https://github.com/markusschloesser/MackieC4_P3/tree/encodermaphistory
